name: CI Build & Auto-Deploy to Main

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'dist/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Commit dist to main
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -f dist
          git diff --cached --quiet || git commit -m "chore: rebuild dist [skip ci]"
          git push origin main